// app/head.tsx
export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        integrity="sha512-y9QoOSfpYQYjwM4RHsFtyFRUFavjvDq4qFZ6KoWT/qT+1sU7T5TOelAhUYa9Vq54jaRfdL/2tNH91uWg5Dg8Xg=="
        crossOrigin="anonymous"
        referrerPolicy="no-referrer"
      />
    </>
  );
}
